# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(793, 553)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.lblExercisesChanged = QtGui.QLabel(self.centralwidget)
        self.lblExercisesChanged.setObjectName(_fromUtf8("lblExercisesChanged"))
        self.horizontalLayout_4.addWidget(self.lblExercisesChanged)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.exercisesTableView = QtGui.QTableView(self.centralwidget)
        self.exercisesTableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.exercisesTableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.exercisesTableView.setObjectName(_fromUtf8("exercisesTableView"))
        self.exercisesTableView.horizontalHeader().setCascadingSectionResizes(False)
        self.exercisesTableView.horizontalHeader().setDefaultSectionSize(150)
        self.exercisesTableView.horizontalHeader().setStretchLastSection(True)
        self.exercisesTableView.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout.addWidget(self.exercisesTableView)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.loadDataBtn = QtGui.QPushButton(self.centralwidget)
        self.loadDataBtn.setObjectName(_fromUtf8("loadDataBtn"))
        self.horizontalLayout_3.addWidget(self.loadDataBtn)
        self.saveDataBtn = QtGui.QPushButton(self.centralwidget)
        self.saveDataBtn.setObjectName(_fromUtf8("saveDataBtn"))
        self.horizontalLayout_3.addWidget(self.saveDataBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.exerciseName = QtGui.QComboBox(self.centralwidget)
        self.exerciseName.setEditable(True)
        self.exerciseName.setObjectName(_fromUtf8("exerciseName"))
        self.exerciseName.addItem(_fromUtf8(""))
        self.exerciseName.addItem(_fromUtf8(""))
        self.exerciseName.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.exerciseName)
        self.exerciseDate = QtGui.QDateEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exerciseDate.sizePolicy().hasHeightForWidth())
        self.exerciseDate.setSizePolicy(sizePolicy)
        self.exerciseDate.setCalendarPopup(True)
        self.exerciseDate.setObjectName(_fromUtf8("exerciseDate"))
        self.horizontalLayout_2.addWidget(self.exerciseDate)
        self.addExerciseBtn = QtGui.QPushButton(self.centralwidget)
        self.addExerciseBtn.setObjectName(_fromUtf8("addExerciseBtn"))
        self.horizontalLayout_2.addWidget(self.addExerciseBtn)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_2.addWidget(self.line_3)
        self.lblSetsChanged = QtGui.QLabel(self.centralwidget)
        self.lblSetsChanged.setObjectName(_fromUtf8("lblSetsChanged"))
        self.horizontalLayout_2.addWidget(self.lblSetsChanged)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_2.addWidget(self.line_2)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.totalSetsWeightLcd = QtGui.QLCDNumber(self.centralwidget)
        self.totalSetsWeightLcd.setObjectName(_fromUtf8("totalSetsWeightLcd"))
        self.horizontalLayout_2.addWidget(self.totalSetsWeightLcd)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.setsTableView = QtGui.QTableView(self.centralwidget)
        self.setsTableView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.setsTableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.setsTableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.setsTableView.setObjectName(_fromUtf8("setsTableView"))
        self.setsTableView.horizontalHeader().setDefaultSectionSize(150)
        self.setsTableView.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.setsTableView)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.weight = QtGui.QSpinBox(self.centralwidget)
        self.weight.setSingleStep(5)
        self.weight.setProperty("value", 35)
        self.weight.setObjectName(_fromUtf8("weight"))
        self.horizontalLayout.addWidget(self.weight)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.count = QtGui.QSpinBox(self.centralwidget)
        self.count.setProperty("value", 10)
        self.count.setObjectName(_fromUtf8("count"))
        self.horizontalLayout.addWidget(self.count)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.setCount = QtGui.QSpinBox(self.centralwidget)
        self.setCount.setProperty("value", 1)
        self.setCount.setObjectName(_fromUtf8("setCount"))
        self.horizontalLayout.addWidget(self.setCount)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.addSetBtn = QtGui.QPushButton(self.centralwidget)
        self.addSetBtn.setObjectName(_fromUtf8("addSetBtn"))
        self.horizontalLayout.addWidget(self.addSetBtn)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.clearExerciseBtn = QtGui.QPushButton(self.centralwidget)
        self.clearExerciseBtn.setObjectName(_fromUtf8("clearExerciseBtn"))
        self.horizontalLayout.addWidget(self.clearExerciseBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.exerciseName.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ко́чка", None))
        self.label_5.setText(_translate("MainWindow", "Журнал тренировок", None))
        self.lblExercisesChanged.setText(_translate("MainWindow", "<font style=\" color:#a9a9a9;\">Изменения</font>", None))
        self.loadDataBtn.setText(_translate("MainWindow", "Обновить", None))
        self.saveDataBtn.setText(_translate("MainWindow", "Сохранить", None))
        self.label_6.setText(_translate("MainWindow", "Тренировка", None))
        self.exerciseName.setItemText(0, _translate("MainWindow", "тяга", None))
        self.exerciseName.setItemText(1, _translate("MainWindow", "жим", None))
        self.exerciseName.setItemText(2, _translate("MainWindow", "присед", None))
        self.exerciseDate.setDisplayFormat(_translate("MainWindow", "yyyy.MM.dd", None))
        self.addExerciseBtn.setText(_translate("MainWindow", "Записать в журнал", None))
        self.lblSetsChanged.setText(_translate("MainWindow", "<font style=\" color:#a9a9a9;\">Изменения</font>", None))
        self.label_4.setText(_translate("MainWindow", "Всего:", None))
        self.label_2.setText(_translate("MainWindow", "кг", None))
        self.label_3.setText(_translate("MainWindow", "раз", None))
        self.label.setText(_translate("MainWindow", "подходов", None))
        self.addSetBtn.setText(_translate("MainWindow", "Добавить сет", None))
        self.clearExerciseBtn.setText(_translate("MainWindow", "Очистить сеты", None))

